### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by juliocvergarah** [azoner/pyx12#48]
I tried using this module with Python3. Are there any plans to make it compatible with Python3?

**Comment by azoner** [comment]
I merged a pull request a few days ago that begins python 3 support. Unit tests are passing under both python 2 and 3.  Included scripts are failing.

See https://github.com/azoner/pyx12/tree/py3-fix-scripts

**Comment by azoner** [comment]
I will publish a new release to pypi when python 3 support is complete.

**Comment by KennyMonster** [comment]
Is Python 3 support still in the works, or is it something I would need to take on myself? Thanks!

**Comment by rubic** [comment]
Maybe related to Python 3 support, but when I tried running the validator against the example file, I got an error:

`$ x12valid ~/Projects/pyx12/pyx12/examples/example834_5010.txt 
Traceback (most recent call last):
  File "/home/jbauer/.virtualenvs/salsa/bin/x12valid", line 8, in <module>
    sys.exit(main())
  File "/home/jbauer/.virtualenvs/salsa/lib/python3.7/site-packages/pyx12/scripts/x12valid.py", line 90, in main
    if args.verbose > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
`

**Comment by ddw360** [comment]
I had the same problem - changing the following starting at line 90 in x12valid.py solved it for me:

```diff
+ if args.verbose is not None and type(args.verbose).__name__ == 'int':
- if args.verbose > 0:
-     logger.setLevel(logging.DEBUG)
+     if args.verbose > 0:
+         logger.setLevel(logging.DEBUG)
```

**Comment by eddyizm** [comment]
Is this still open? Giving a first pass on this but don't see much documentation. I made the change mentioned by @ddw360 but getting a different error. Would love to contribute to this project.

**Comment by lucaswiman** [comment]
The py3-port branch includes my PR #54 that fixed a bunch of compatibility issues. I've been using that branch on python 3.6 and 3.7 with no issues. It would be good to ship that to pypi, but it's usable as-is: https://github.com/azoner/pyx12/tree/py3-port

**Comment by menacher** [comment]
@lucaswiman is there a way to do pip install for this python 3? Or do you copy over the source code and use it with python 3?

**Comment by lucaswiman** [comment]
@menacher https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/

**Comment by azoner** [comment]
Closing — Python 3 support has been the only supported path for some time now.

Thanks to everyone on this thread who helped get there over the years, especially @ddw360 (#69) and @lucaswiman (#54, the original \`py3-port\` branch). The recent py3-modernize push (#87) cleaned out the last py2-era idioms.

**Current status:**
- Python 3-only — supports **3.11, 3.12, 3.13, 3.14**
- Latest release: [v3.1.0](https://github.com/azoner/pyx12/releases/tag/v3.1.0) (just shipped) — \`pip install pyx12\`
- mypy strict + ruff in CI
