### ISSUE TITLE
Error when parsing a 271 file

### ISSUE THREAD

**Issue by harriettxing** [azoner/pyx12#62]
harriettxing2001@instance-1:~/demo/python$ x12valid 271Sample.txt
Traceback (most recent call last):
  File "/usr/local/bin/x12valid", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pyx12/scripts/x12valid.py", line 155, in main
    fd_997=fd_997, fd_html=fd_html, fd_xmldoc=None, map_path=args.map_path):
  File "/usr/local/lib/python2.7/dist-packages/pyx12/x12n_document.py", line 147, in x12n_document
    raise pyx12.errors.EngineError(err_str)
pyx12.errors.EngineError: Map not found.  icvn=00501, fic=HB, vriic=005010X279A1
harriettxing2001@instance-1:~/demo/python$ 
[271Sample.txt](https://github.com/azoner/pyx12/files/3387675/271Sample.txt)

**Comment by azoner** [comment]
I have not converted many of the 4010 maps to 5010, including the 271.  If you have a copy of the implementation guide, it would be great if you could work on that.

See [https://github.com/azoner/pyx12/blob/master/pyx12/map/271.4010.X092.A1.xml](https://github.com/azoner/pyx12/blob/master/pyx12/map/271.4010.X092.A1.xml)
